//! `x completion`: shell completion scripts generated from the CLI grammar.
//!
//! Generated by `clap_complete` straight from the parsed [`crate::Cli`] tree,
//! so new commands and flags appear in completions automatically and the five
//! shells stay in sync with zero per-shell maintenance.

use clap::CommandFactory;
use clap_complete::{generate, shells};
use x_core::error::Result;

use crate::format::Renderer;

/// Supported shells.
#[derive(Debug, Clone, Copy, clap::ValueEnum)]
pub enum ShellArg {
    /// Bash.
    Bash,
    /// Zsh.
    Zsh,
    /// Fish.
    Fish,
    /// PowerShell.
    Powershell,
    /// Elvish.
    Elvish,
}

/// `x completion <shell>` arguments.
#[derive(Debug, clap::Args)]
pub struct CompletionArgs {
    /// Shell to generate the script for.
    pub shell: ShellArg,
}

impl From<ShellArg> for shells::Shell {
    fn from(value: ShellArg) -> Self {
        match value {
            ShellArg::Bash => shells::Shell::Bash,
            ShellArg::Zsh => shells::Shell::Zsh,
            ShellArg::Fish => shells::Shell::Fish,
            ShellArg::Powershell => shells::Shell::PowerShell,
            ShellArg::Elvish => shells::Shell::Elvish,
        }
    }
}

/// Route a `x completion` invocation.
pub fn dispatch(
    _context: &x_core::SystemContext,
    renderer: &mut Renderer,
    args: &CompletionArgs,
) -> Result<i32> {
    let mut buffer = Vec::new();
    let mut cli = crate::Cli::command();
    let bin_name = cli.get_name().to_string();
    let shell: shells::Shell = args.shell.into();
    generate(shell, &mut cli, bin_name, &mut buffer);
    renderer.raw(&buffer)?;
    renderer.line("# install: save the output to your completion dir (see your shell's docs)")?;
    Ok(0)
}
